cc_binary(
    name = "opencv_example",
    srcs = [
        "main.cpp",
    ],
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-unused-parameter",
        "-Wno-unused-variable",
        "-Wno-address",
    ],
    deps = [
        "@opencv",
    ],
)
